const planetData = [
    {
    name: "mercury",
    des: "Mercury is the smallest planet in the Solar System and the closest to the Sun. Its orbit around the Sun takes 87.97 Earth days, the shortest of all the Sun's planets. Mercury is one of four terrestrial planets in the Solar System, and is a rocky body like Earth.",
    color: "#419EBB",
    img1: require('./assets/planet-mercury.svg').default,
    img2: require('./assets/planet-mercury-internal.svg').default,
    img3: require('./assets/geology-mercury.png'),
    rotate: '58.6 days',
    revolution: '87.97 days',
    rad: '2,439.7 km',
    avg: '430°c',
  },
  {
    name: "VENUS",
    des: "Venus is the second planet from the Sun. It is named after the Roman goddess of love and beauty. As the brightest natural object in Earth's night sky after the Moon, Venus can cast shadows and can be, on rare occasions, visible to the naked eye in broad daylight.",
    color: '#EDA249',
    img1: require('./assets/planet-venus.svg').default,
    img2: require('./assets/planet-venus-internal.svg').default,
    img3: require('./assets/geology-venus.png'),
    rotate: '243 days',
    revolution: '224.7 days',
    rad: '6,051.8 km',
    avg: '471°c',
  },
  {
    name: "EARTH",
    des: "Third planet from the Sun and the only known planet to harbor life. About 29.2% of Earth's surface is land with remaining 70.8% is covered with water. Earth's distance from the Sun, physical properties and geological history have allowed life to evolve and thrive.",
    color: '#6D2ED5',
    img1: require('./assets/planet-earth.svg').default,
    img2: require('./assets/planet-earth-internal.svg').default,
    img3: require('./assets/geology-earth.png'),
    rotate: '0.99 days',
    revolution: '365.26 days',
    rad: '6,371 km',
    avg: '16°c',
  },
  {
    name: "Mars",
    des: 'The fourth planet from the Sun and the second-smallest planet in the Solar System.',
    color: '#D14C32',
    img1: require('./assets/planet-mars.svg').default,
    img2: require('./assets/planet-mars-internal.svg').default,
    img3: require('./assets/geology-mars.png'),
    rotate: '24.6 hours',
    revolution: '687 days',
    rad: '3,389.5 km',
    avg: '-80°F',
  },  
  {
    name: "jupiter",
    des: "Jupiter is the fifth planet from the Sun and the largest in the Solar System. It is a gas giant with a mass two and a half times that of all the other planets in the Solar System combined, but less than one-thousandth the mass of the Sun.",
    color: '#CD5120',
    img1: require('./assets/planet-jupiter.svg').default,
    img2: require('./assets/planet-jupiter-internal.svg').default,
    img3: require('./assets/geology-jupiter.png'),
    rotate: '24.6 hours',
    revolution: '687 days',
    rad: '3,389.5 km',
    avg: '-80°F',
  },
  {
    name: "saturn",
    des: "Saturn is the sixth planet from the Sun and the second-largest in the Solar System, after Jupiter. It is a gas giant with an average radius of about nine and a half times that of Earth. It only has one-eighth the average density of Earth.",
    color: '#CD5120',
    img1: require('./assets/planet-saturn.svg').default,
    img2: require('./assets/planet-saturn-internal.svg').default,
    img3: require('./assets/geology-saturn.png'),
    rotate: '10.8 hours',
    revolution: '29.46 years',
    rad: '58,232 km',
    avg: '-138°c',
  },
  {
    name: "Uranus",
    des: "Uranus is the seventh planet from the Sun. Its name is a reference to the Greek god of the sky, Uranus according to Greek mythology, was the great-grandfather of Ares. It has the third-largest planetary radius and fourth-largest planetary mass in the Solar System.",
    color: '#1EC1A2',
    img1: require('./assets/planet-uranus.svg').default,
    img2: require('./assets/planet-uranus-internal.svg').default,
    img3: require('./assets/geology-uranus.png'),
    rotate: '17.2 hours',
    revolution: '84 years',
    rad: '25,362 km',
    avg: '-195°c',
  },
  {
    name: "Neptune",
    des: "Neptune is the eighth and farthest-known Solar planet from the Sun. In the Solar System, it is the fourth-largest planet by diameter, the third-most-massive planet, and the densest giant planet. It is 17 times the mass of Earth, more massive than its near-twin Uranus.",
    color: '#2D68F0',
    img1: require('./assets/planet-neptune.svg').default,
    img2: require('./assets/planet-neptune-internal.svg').default,
    img3: require('./assets/geology-neptune.png'),
    rotate: '16.08 hours',
    revolution: '164.79 years',
    rad: '24,622 km',
    avg: '-201°c',
  },
  

]

  export default planetData;